import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import CustomEditor from '../components/CustomEditor';
import { MdOutlinePalette } from 'react-icons/md';
import { AiOutlineEye } from 'react-icons/ai';
import ShowCase from '../components/ShowCase';
import Featured from '../components/Featured';
import Link from 'next/link';

const Home: NextPage = () => {
  const scrollToShowcase = () => {
    const anchor = document.querySelector('#showcase');
    if (anchor)
      anchor.scrollIntoView({
        behavior: 'smooth',
        block: 'center',
      });
  };

  return (
    <div className={styles.app}>
      <Head>
        <title>Canvas Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className={styles.intro}>
        <div className={styles.container}>
          <p className={styles.headline}>
            Realize the creative power of JavaScript and{' '}
            <pre>{`<canvas />`}</pre>
          </p>

          <p className={styles.headline2}>
            Create some Generative art and share your pieces with others
          </p>

          <div className={styles.actions}>
            <button className={styles.btn} onClick={scrollToShowcase}>
              <AiOutlineEye size={20} /> <span>View Gallery</span>
            </button>
            <Link href="/create">
              <button className={`${styles.btn}`}>
                {' '}
                <MdOutlinePalette size={20} /> <span>Create My Piece</span>
              </button>
            </Link>
          </div>
        </div>

        <div className={styles.illustration}>
          <Image
            width={800}
            height={600}
            src="/intro-img-transparent.png"
            objectFit="contain"
          />
        </div>
      </section>

      <CustomEditor />

      <ShowCase />

      <Featured />
    </div>
  );
};

export default Home;
