import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import dynamic from 'next/dynamic';
import CodeEditor from '../components/CodeEditor';
import CustomEditor from '../components/CustomEditor';
import { MdOutlinePalette } from 'react-icons/md';

const Home: NextPage = () => {
  const MonacoEditor = dynamic(import('react-monaco-editor'), { ssr: false });

  return (
    <div className={styles.app}>
      <Head>
        <title>Canvas Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className={styles.intro}>
        <div className={styles.container}>
          <p className={styles.headline}>
            Realize the creative power of JavaScript and{' '}
            <pre>{`<canvas />`}</pre>
          </p>

          <p className={styles.headline2}>
            Create some Generative art and share your pieces with others
          </p>

          <div className="actions">
            <button className={styles.btn}>View Gallery</button>
            <button className={`${styles.btn}`}>
              {' '}
              <MdOutlinePalette /> Create My Piece
            </button>
          </div>
        </div>

        <div className={styles.illustration}>
          <Image
            width={800}
            height={600}
            src="/intro-img-transparent.png"
            objectFit="contain"
          />
        </div>
      </section>

      <CustomEditor />

      <CodeEditor />
    </div>
  );
};

export default Home;
